### ISSUE TITLE
exit() called instead of sys.exit()

### ISSUE THREAD

**Issue by bgyori** [shubham-goel/UniGen#2]
I noticed that in several places in UniGen2.py, exit() is called (e.g.
https://github.com/shubham-goel/UniGen/blob/master/UniGen2.py#L35) but it is not explicitly imported. These lines should either be modified to use `sys.exit`, or alternatively `from sys import exit` should be imported. I am getting errors due to this in some cases.

**Comment by sumith1896** [comment]
@bgyori Thanks for the report. This repository is just a fork of UniGen, the original repo resides [here](https://bitbucket.org/kuldeepmeel/unigen). You would want to post this there. Closing this...
